name: terraform
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: "1.14.3"
    - name: Setup Terraform
      uses: marocchino/setup-terraform@v1.0.1
      with:
        version: "0.12.26"
    - name: terraform validate
      run: terraform init && terraform validate
    - name: Run tests
      run: go test -v ./...
